name: JCrypsi CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Install Ubuntu dependecies
        run: bash ./scripts/install_ubuntu_deps

      - name: Run test
        run: make test
      
      - name: Build
        run: make build
      
      - name: Run Example App
        run: java -jar target/app.jar